"""Build an allowlisted site with a complete, immutable runtime per release."""
from pathlib import Path
import ast
import hashlib
import json
import shutil

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "dist"
CORE = ["__init__.py", "_version.py", "models.py", "analysis.py", "plate_io.py", "project.py", "wells.py", "browser_batch.py"]
ASSETS = ["index.html", "styles.css", "app.js", "worker.js", "favicon.svg"]


def build():
    # This directory is generated by this script, not a source or upload directory.
    if OUT.is_symlink():
        raise RuntimeError("Refusing a symlinked output directory")
    sources = {name: (ROOT / "web" / name).read_bytes() for name in ASSETS}
    sources.update({f"core/folding_practical/{name}": (ROOT / "folding_practical" / name).read_bytes() for name in CORE})
    digest = hashlib.sha256()
    for name, content in sorted(sources.items()):
        digest.update(name.encode("utf-8") + b"\0" + hashlib.sha256(content).digest())
    build_id = digest.hexdigest()[:20]
    release_path = f"releases/{build_id}"
    # Read the version from the source being built, including isolated test builds.
    version_tree = ast.parse(sources["core/folding_practical/_version.py"].decode("utf-8"))
    version = next(ast.literal_eval(node.value) for node in version_tree.body
                   if isinstance(node, ast.Assign)
                   and any(isinstance(target, ast.Name) and target.id == "__version__" for target in node.targets))
    manifest = {
        "software_version": version, "build_id": build_id,
        "release_index": f"{release_path}/index.html",
        "pyodide": "0.27.7", "python": "3.12.7",
        "packages": {"numpy": "2.0.2", "scipy": "1.14.1", "pandas": "2.2.3"},
        "core_sha256": {name: hashlib.sha256(sources[f"core/folding_practical/{name}"]).hexdigest() for name in CORE},
    }
    if OUT.exists():
        shutil.rmtree(OUT)
    for name, content in sources.items():
        # Stable paths support existing links; new pages always use the release.
        for target in (OUT / name, OUT / release_path / name):
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
    index = sources["index.html"].decode("utf-8").replace(
        "<title>", f'<meta name="application-build" content="{build_id}">\n  <title>', 1)
    (OUT / release_path / "index.html").write_text(index, encoding="utf-8")
    for asset in ("app.js", "styles.css", "favicon.svg"):
        index = index.replace(f'"./{asset}"', f'"./{release_path}/{asset}"')
    (OUT / "index.html").write_text(index, encoding="utf-8")
    for directory in (OUT, OUT / release_path):
        (directory / "build-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (OUT / ".nojekyll").touch()
    print(f"Built release {build_id}: {len(ASSETS)} assets and {len(CORE)} core modules in {OUT}")
    return manifest


if __name__ == "__main__":
    build()
