"""Build a strictly allowlisted static site; never package measurement files."""
from pathlib import Path
import hashlib
import json
import shutil
import sys

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "dist"
CORE = ["__init__.py", "_version.py", "models.py", "analysis.py", "plate_io.py", "project.py", "wells.py"]
ASSETS = ["index.html", "styles.css", "app.js", "worker.js", "favicon.svg"]

def build():
    # This directory is generated by this script, not a source or upload directory.
    if OUT.is_symlink():
        raise RuntimeError("Refusing a symlinked output directory")
    if OUT.exists():
        shutil.rmtree(OUT)
    (OUT / "core" / "folding_practical").mkdir(parents=True)
    hashes = {}
    for filename in CORE:
        source = ROOT / "folding_practical" / filename
        target = OUT / "core" / "folding_practical" / filename
        shutil.copyfile(source, target)
        hashes[filename] = hashlib.sha256(target.read_bytes()).hexdigest()
    for filename in ASSETS:
        shutil.copyfile(ROOT / "web" / filename, OUT / filename)
    (OUT / ".nojekyll").touch()
    sys.path.insert(0, str(ROOT))
    from folding_practical._version import __version__
    manifest = {"software_version": __version__, "pyodide": "0.27.7", "python": "3.12.7",
                "packages": {"numpy": "2.0.2", "scipy": "1.14.1", "pandas": "2.2.3"},
                "core_sha256": hashes}
    (OUT / "build-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Built {len(ASSETS)} assets and {len(CORE)} core modules in {OUT}")

if __name__ == "__main__":
    build()
