#!/usr/bin/env python3
"""Generate deterministic native-Python reference results for browser parity tests.

The fixture contains synthetic teaching data only.  Each case is imported and
fit through the public analysis-service contract, which is the same contract
used by the Pyodide web worker.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Iterable, Optional

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from folding_practical.analysis import dispatch  # noqa: E402
from folding_practical.models import (  # noqa: E402
    four_parameter_logistic,
    two_state_denaturation_signal,
)

OUTPUT = ROOT / "tests" / "fixtures" / "browser_reference.json"


def _csv(rows: Iterable[tuple[Optional[float], Optional[float]]]) -> str:
    lines = ["GuHCl concentration (M),raw fluorescence values"]
    for concentration, signal in rows:
        x = "" if concentration is None else f"{concentration:.12g}"
        y = "NA" if signal is None else f"{signal:.12g}"
        lines.append(f"{x},{y}")
    return "\n".join(lines) + "\n"


def _two_state(x: np.ndarray) -> np.ndarray:
    return two_state_denaturation_signal(
        x,
        folded_intercept=1100.0,
        folded_slope=-18.0,
        unfolded_intercept=155.0,
        unfolded_slope=7.0,
        delta_g_h2o_kj_mol=20.0,
        m_value_kj_mol_m=6.25,
        temperature_k=298.15,
    )


def _case(name: str, rows: list[tuple[Optional[float], Optional[float]]], model: str) -> dict:
    import_request = {
        "action": "import_series",
        "filename": f"synthetic_{name}.csv",
        "text": _csv(rows),
        "settings": {"group_name": f"Synthetic {name}", "temperature_k": 298.15},
        "notes": "Synthetic browser/native parity fixture; not experimental data.",
    }
    imported = dispatch(import_request)
    if not imported.get("ok"):
        raise RuntimeError(f"Could not import {name}: {imported}")
    fit_request = {
        "action": "fit",
        "project": imported["data"]["project"],
        "model": model,
    }
    fitted = dispatch(fit_request)
    if not fitted.get("ok"):
        raise RuntimeError(f"Could not fit {name}: {fitted}")
    return {
        "import_request": import_request,
        "fit_model": model,
        "native_import": imported,
        "native_fit": fitted,
    }


def build_reference() -> dict:
    ideal_x = np.linspace(0.0, 6.0, 25)
    ideal_y = _two_state(ideal_x)

    noisy_x = np.linspace(0.0, 6.0, 25)
    index = np.arange(noisy_x.size, dtype=float)
    noisy_y = _two_state(noisy_x) + 13.0 * np.sin(1.71 * index) + 5.0 * np.cos(0.37 * index)

    partial_x = np.linspace(0.0, 2.0, 12)
    partial_y = _two_state(partial_x)

    flat_x = np.linspace(0.0, 6.0, 16)
    flat_y = np.full_like(flat_x, 500.0)

    missing_x = np.linspace(0.0, 6.0, 17)
    missing_y = _two_state(missing_x)
    missing_rows: list[tuple[Optional[float], Optional[float]]] = list(
        zip(missing_x.tolist(), missing_y.tolist())
    )
    missing_rows.insert(4, (None, 911.0))
    missing_rows.insert(12, (4.125, None))

    replicate_x = np.repeat(np.linspace(0.0, 6.0, 11), 3)
    replicate_index = np.arange(replicate_x.size, dtype=float)
    replicate_y = four_parameter_logistic(replicate_x, 1040.0, 170.0, 3.15, 0.34)
    replicate_y = replicate_y + 7.0 * np.sin(2.3 * replicate_index)

    cases = {
        "ideal": _case("ideal", list(zip(ideal_x.tolist(), ideal_y.tolist())), "two_state"),
        "noisy": _case("noisy", list(zip(noisy_x.tolist(), noisy_y.tolist())), "compare"),
        "partial": _case("partial", list(zip(partial_x.tolist(), partial_y.tolist())), "two_state"),
        "flat": _case("flat", list(zip(flat_x.tolist(), flat_y.tolist())), "logistic"),
        "missing": _case("missing", missing_rows, "two_state"),
        "replicate": _case(
            "replicate",
            list(zip(replicate_x.tolist(), replicate_y.tolist())),
            "logistic",
        ),
    }
    return {
        "schema_version": "browser-reference-1.0",
        "description": "Deterministic synthetic cases generated by native analysis.dispatch.",
        "tolerances": {
            "parameter_relative": 1e-3,
            "parameter_absolute": 1e-6,
            "prediction_scale_fraction": 2e-6,
            "prediction_absolute_floor": 1e-6,
        },
        "cases": cases,
    }


def main() -> None:
    reference = build_reference()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(reference, indent=2, sort_keys=True, allow_nan=False) + "\n"
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(reference['cases'])} synthetic cases)")


if __name__ == "__main__":
    main()
